
#[CONFIGMAP-SECRET]
#1_employee-service_[ConfigMap-Secret].yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-service
  namespace: default
  labels:
    app: microservicio-employee-service
    role: backend
    stage: production
    version: v1.0.0
data:
  #-------------------------------------------------------------------#
  #----------- CONFIGURACION PROPERTIES [employee-service] -----------#
  #-------------------------------------------------------------------#
  application.properties: |-
    grupoconfig01.nombres=CESAR GUERRA
    grupoconfig01.dni=41816133
    propiedades.config.valor_01=JAVAMAN
    propiedades.config.valor_02=MAKTUP
    ingress.dns.employee=http://capacitacion.microservicios.employee
    ingress.dns.department=http://capacitacion.microservicios.department
    ingress.dns.organization=http://capacitacion.microservicios.organization
    ingress.dns.utlcapadb=http://capacitacion.microservicios.utlcapadb

---

apiVersion: v1
kind: Secret
metadata:
  name: employee-service-secret
  namespace: default
  labels:
    app: microservicio-employee-service
    role: backend
    stage: production
    version: v1.0.0
  #-------------------------------------------------------------------#
  #---------------------- CONFIGURACION SECRETs ----------------------#
  #--------- Formato BASE64 (https://www.base64encode.net/) ----------#
  #-------------------------------------------------------------------#
data:
  BOOTADMIN_USUARIO: YWRtaW4=
  BOOTADMIN_PASSWORD: YWRtaW4=

